server:
  port: 9527

spring:
  application:
    name: gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 根据微服务名动态路由
      routes:
        - id: payment-route1 # 唯一即可
          #uri: http://localhost:8001 # 匹配地址
          #lb 负载
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/queryPayment/** #匹配地址
            - After=2020-12-03T15:19:14.769+08:00[Asia/Shanghai]
        - id: payment-route2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/create
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka