server:
  port: 8001


spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

eureka:
  client:
    #注册到 eureka注册中心
    register-with-eureka: true
    #是否从 注册中心抓取 已有的注册信息，在集群的时候用到
    fetch-registry: true
    service-url:
      # 注册到单机的Eureka
      #defaultZone: http://localhost:7001/eureka
      #注册到集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  # 信息显示
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    # eureka 客户端向注册中心发送心跳的时间间隔 默认30s
    lease-expiration-duration-in-seconds: 2
    #eureka 服务端在收到最后一次心跳后等待时间上限，默认90s
    lease-renewal-interval-in-seconds: 2


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.weimin.payment.pojo