server:
  port: 9002

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.169.57:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'