server:
  port: 8002


spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://123.56.169.57:3306/springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: WmwM1220..

eureka:
  client:
    #注册到 eureka注册中心
    register-with-eureka: true
    #是否从 注册中心抓取 已有的注册信息，在集群的时候用到
    fetch-registry: true
    service-url:
      # 注册到单机的Eureka
      #defaultZone: http://localhost:7001/eureka
      #注册到集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.weimin.payment.pojo