server:
  port: 8008

spring:
  application:
    name: hystrix-payment-8008

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka