server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weimin1998/microservice-config-weimin.git
          search-paths:
            - microservice-config-weimin
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka



management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

